### ISSUE TITLE
Size mismatch

### ISSUE THREAD

**Issue by mratsim** [xternalz/WideResNet-pytorch#1]
Hey there,

I'm trying WideResNet on the following [dataset](https://www.kaggle.com/mratsim/planet-understanding-the-amazon-from-space/starting-kit-for-pytorch-deep-learning), which consists of 256x256x3 images which should be classified into 17 classes.

However I have a size issue on the network. With a batch size of 1, I expected a 1x17 output but I get a 64x17 output. With a batch size of 8 I get 512 x 17 output.

I'm trying to understand the shapes of the tensors at each stage with with the following prints:

```python
def forward(self, x):
        print(x)
        out = self.conv1(x)
        print(out)
        out = self.block1(out)
        print(out)
        out = self.block2(out)
        print(out)
        out = self.block3(out)
        print(out)
        out = self.relu(self.bn1(out))
        print(out)
        out = F.avg_pool2d(out, 8)
        print(out)
        out = out.view(-1, self.nChannels)
        print(out)
        out = self.fc(out)
        print(out)
        return out
```

```bash
$  python main.py
Variable containing:
...
[torch.FloatTensor of size 1x3x256x256]

Variable containing:
...
[torch.FloatTensor of size 1x16x256x256]

Variable containing:
...
[torch.FloatTensor of size 1x64x256x256]

Variable containing:
...
[torch.FloatTensor of size 1x128x128x128]

Variable containing:
...
[torch.FloatTensor of size 1x256x64x64]

Variable containing:
...
[torch.FloatTensor of size 1x256x64x64]

Variable containing:
...
[torch.FloatTensor of size 1x256x8x8]

Variable containing:
...
[torch.FloatTensor of size 64x256]

Variable containing:
...
[torch.FloatTensor of size 64x17]
```

**Comment by xternalz** [comment]
The Wide-ResNets in this repo are designed specifically to work with 32x32 images. For 32x32 input images (e.g., CIFAR-10/100), the feature maps right before `avg_pool2d` are of 8x8 spatial sizes, and the `avg_pool2d` reduces them to 1x1 by pooling over a 8x8 window. 

To use it on 256x256 images, you are supposed to modify the network architecture accordingly. You may want to refer to the model definition of ImageNet-based Wide-ResNet-50-2 [https://github.com/szagoruyko/wide-residual-networks/blob/master/pretrained/README.md](https://github.com/szagoruyko/wide-residual-networks/blob/master/pretrained/README.md).

**Comment by hturki** [comment]
would changing the avgpool line to something like nn.AdaptiveAvgPool2d((1, 1)) do the trick? or does nChannels also need to change?
