### ISSUE TITLE
Accuracy

### ISSUE THREAD

**Issue by TheRevanchist** [xternalz/WideResNet-pytorch#2]
Hi,

Did you manage to get the same accuracy as in the paper?

Cheers!

**Comment by xternalz** [comment]
Definitely, the code strictly mirrors the official Torch version [https://github.com/szagoruyko/wide-residual-networks](https://github.com/szagoruyko/wide-residual-networks).

**Comment by isht8** [comment]
I think it would be good if you include a table in your readme comparing results of the torch and pytorch codes on cifar10, cifar100 & imagenet. That would be very convincing.
